<?php

$listItems = array(
    'Fruits and Vegetables' => array(
        'Apples',
        'Bananas',
        'Oranges',
    ),
    'Bakery' => array(
        'Bread',
    ),
    'Baking Goods' => array(
        'Eggs',
        'Sugar',
    ),
    'Cleaning' => array(
        'Bleach',
        'Washing tablets',
    ),
    'Dairy' => array(
        'Butter',
        'Milk',
    ),
    'Juice' => array(
        'Apple juice',
        'Orange juice',
    ),
    'Cooked Meat' => array(
        'Sliced ham',
    ),
    'Fresh Meat' => array(
        'Mince',
        'Pork',
        'Sausages',
        'Steak',
        'Turkey',
    ),
    'Condiments, etc.' => array(
        'Vegetable oil',
        'Salt',
        'Sandwich pickle',
        'Vinegar',
    ),
    'Grains and Cereals' => array(
        'Breakfast cereal',
        'Pasta',
    ),
    'Canned Goods' => array(
        'Salmon',
        'Soup',
        'Tinned fruit',
        'Tuna',
    ),
    'Drinks' => array(
        'Coffee',
        'Tea',
        'Bottled water',
    ),
    'Sweets and Biscuits' => array(
        'Biscuits',
        'Chocolate',
    ),
    'Toiletries' => array(
        'Shampoo',
        'Shower gel',
        'Toothpaste',
    ),
    'Frozen Food' => array(
        'Chicken',
        'Chips',
        'Fish',
        'Frozen vegetables',
        'Ice cream',
        'Pies',
        'Pizza',
    ),
);

?>